In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kartik2112/fraud-detection")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/kartik2112/fraud-detection/1.archive...

100%|██████████| 202M/202M [00:01<00:00, 144MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/kartik2112/fraud-detection/versions/1

In [ ]:

!cp -r "/root/.cache/kagglehub/datasets/kartik2112/fraud-detection/versions/1" "./Farud Detection Syetem"

In [1]:
import os

os.listdir("./Farud Detection Syetem/1")

['fraudTrain.csv', 'fraudTest.csv']

In [2]:
import pandas as pd
dataframes=[]

for file_name in os.listdir("./Farud Detection Syetem/1"):
  with open(f"./Farud Detection Syetem/1/{file_name}", "r") as f:
    dataframes.append(pd.read_csv(f))

In [3]:
train_df,test_df=dataframes

In [4]:
train_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [5]:
train_df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [6]:
train_df["is_fraud"].value_counts()

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

In [7]:
unnessary_columns_for_fraud_detection=["Unnamed: 0","cc_num","trans_num","first","last","unix_time","merchant","street"]

In [8]:
train_df=train_df.drop(columns=unnessary_columns_for_fraud_detection)
test_df=test_df.drop(columns=unnessary_columns_for_fraud_detection)

In [9]:
train_df["age"]=2026-pd.to_datetime(train_df["dob"]).dt.year
train_df=train_df.drop(columns="dob")

In [10]:
test_df["age"]=2026-pd.to_datetime(test_df["dob"]).dt.year
test_df=test_df.drop(columns="dob")

In [11]:
train_df.columns

Index(['trans_date_trans_time', 'category', 'amt', 'gender', 'city', 'state',
       'zip', 'lat', 'long', 'city_pop', 'job', 'merch_lat', 'merch_long',
       'is_fraud', 'age'],
      dtype='object')

In [12]:
train_df=pd.get_dummies(train_df,columns=["gender","category"],dtype=int)
test_df=pd.get_dummies(test_df,columns=["gender","category"],dtype=int)

In [62]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [13]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

le_city = LabelEncoder()
all_cities = pd.concat([train_df["city"].astype(str), test_df["city"].astype(str)]).unique()
le_city.fit(all_cities)
train_df["city"] = le_city.transform(train_df["city"].astype(str))
test_df["city"] = le_city.transform(test_df["city"].astype(str))

le_state = LabelEncoder()
all_states = pd.concat([train_df["state"].astype(str), test_df["state"].astype(str)]).unique()
le_state.fit(all_states)
train_df["state"] = le_state.transform(train_df["state"].astype(str))
test_df["state"] = le_state.transform(test_df["state"].astype(str))

le_job = LabelEncoder()
all_jobs = pd.concat([train_df["job"].astype(str), test_df["job"].astype(str)]).unique()
le_job.fit(all_jobs)
train_df["job"] = le_job.transform(train_df["job"].astype(str))
test_df["job"] = le_job.transform(test_df["job"].astype(str))

In [14]:
train_df["trans_date_trans_time"]=pd.to_datetime(train_df["trans_date_trans_time"])
test_df["trans_date_trans_time"]=pd.to_datetime(test_df["trans_date_trans_time"])

In [15]:
train_df["trans_year"]=train_df["trans_date_trans_time"].dt.year
test_df["trans_year"]=test_df["trans_date_trans_time"].dt.year

train_df["trans_month"]=train_df["trans_date_trans_time"].dt.month
test_df["trans_month"]=test_df["trans_date_trans_time"].dt.month

train_df["trans_day"]=train_df["trans_date_trans_time"].dt.day
test_df["trans_day"]=test_df["trans_date_trans_time"].dt.day

In [16]:
train_df["trans_hour"]=train_df["trans_date_trans_time"].dt.hour
test_df["trans_hour"]=test_df["trans_date_trans_time"].dt.hour

train_df["trans_min"]=train_df["trans_date_trans_time"].dt.minute
test_df["trans_min"]=test_df["trans_date_trans_time"].dt.minute

train_df["trans_sec"]=train_df["trans_date_trans_time"].dt.second
test_df["trans_sec"]=test_df["trans_date_trans_time"].dt.second

In [17]:
train_df=train_df.drop("trans_date_trans_time",axis=1)
test_df=test_df.drop("trans_date_trans_time",axis=1)

In [18]:
X_train=train_df.drop("is_fraud",axis=1)
X_test=test_df.drop("is_fraud",axis=1)

Y_train=train_df["is_fraud"]
Y_test=test_df["is_fraud"]

In [19]:
from sklearn.linear_model import LogisticRegression

logistic_model=LogisticRegression()
logistic_model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [20]:
from sklearn.ensemble import RandomForestClassifier

random_forest_model=RandomForestClassifier()
random_forest_model.fit(X_train,Y_train)

RandomForestClassifier()

In [21]:
y_train_pred_logistic=logistic_model.predict(X_train)
y_train_pred_random_forest=random_forest_model.predict(X_train)

y_tese_pred_logistic=logistic_model.predict(X_test)
y_tese_pred_random_forest=random_forest_model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score,f1_score

#for logistic regression model
print("="*20+"Logistic Regression Model"+"="*20)

print("Training Accuracy for Logistic Regression Model : ",accuracy_score(Y_train,y_train_pred_logistic))
print("Testing Accuracy for Logistic Regression Model : ",accuracy_score(Y_test,y_tese_pred_logistic))

print("Training F1 Score for Logistic Regression Model : ",f1_score(Y_train,y_train_pred_logistic))
print("Testing F1 Score for Logistic Regression Model : ",f1_score(Y_test,y_tese_pred_logistic))

====================Logistic Regression Model====================
Training Accuracy for Logistic Regression Model :  0.9936483698690882
Testing Accuracy for Logistic Regression Model :  0.9954941256282401
Training F1 Score for Logistic Regression Model :  0.0
Testing F1 Score for Logistic Regression Model :  0.0

In [23]:
#for random forest  model
print("="*20+"Random Forest Classification Model"+"="*20)

print("Training Accuracy for Random Forest Classification Model : ",accuracy_score(Y_train,y_train_pred_random_forest))
print("Testing Accuracy for Random Forest Classification Model : ",accuracy_score(Y_test,y_tese_pred_random_forest))


print("Training F1 Score for Random Forest Classification Model : ",f1_score(Y_train,y_train_pred_random_forest))
print("Testing F1 Score for Random Forest Classification Model : ",f1_score(Y_test,y_tese_pred_random_forest))

====================Random Forest Classification Model====================
Training Accuracy for Random Forest Classification Model :  0.9999984575934602
Testing Accuracy for Random Forest Classification Model :  0.9987403705829745
Training F1 Score for Random Forest Classification Model :  0.9998667554963357
Testing F1 Score for Random Forest Classification Model :  0.8102981029810298